#!/bin/bash
set -e

args=()
for arg in "$@"; do
    if [[ "$arg" == "--relaxed" ]]; then
        export RELAXED_WARNINGS=1
    else
        args+=("$arg")
    fi
done

source "$(dirname "$0")/_env"

RUSTFLAGS="$WASM32_RUSTFLAGS" RUSTDOCFLAGS="$WASM32_RUSTDOCFLAGS" cargo +nightly test --target=wasm32-unknown-unknown --all "${args[@]}"
