#!/bin/bash
set -e

echo "fmt check"
scripts/fmt
echo "facade boundary"
scripts/facade_boundary
echo "check"
scripts/check "$@"
echo "clippy"
scripts/clippy "$@"
echo "tests"
scripts/tests "$@"
echo "docs"
scripts/docs "$@"
